---
title: "Eva Xiao's CV"
author: Eva Xiao
date: "`r Sys.Date()`"
params:
  pdf_mode:
    value: true
output:
  pagedown::html_resume:
    css: ['dd_cv.css', 'resume']
    self_contained: true
---

```{r, include=FALSE}
knitr::opts_chunk$set(
  results='asis', 
  echo = FALSE
)

library(magrittr) # For the pipe
source("cv_printing_functions.r")

# Read in all data and initialize a CV printer object
CV <- create_CV_object(
  data_location = "https://docs.google.com/spreadsheets/d/1OkkeRXII-WniPzShCTPufUcd4kAOAENjhfmy1B89V7c/edit?usp=sharing",  
  pdf_mode = params$pdf_mode
)

```


```{r}
# When in pdf export mode the little dots are unaligned, so fix that with some conditional CSS.
if(params$pdf_mode) {
    cat("
<style>
:root{
  --decorator-outer-offset-left: -6.5px;
}
</style>")
}
```


Aside
================================================================================

Contact {#contact}
--------------------------------------------------------------------------------

```{r}
CV %>% print_contact_info()
```

Awards {#awards}
--------------------------------------------------------------------------------

[The Pulitzer Prize](https://www.pulitzer.org/finalists/staff-wall-street-journal-1), _Finalist for International Reporting in 2021_

[25th Human Rights Press Awards](https://web.archive.org/web/20211104002508/https://humanrightspressawards.org/winners-2021) , _Merit for Explanatory Feature Writing in 2021_

[Society of Publishers in Asia (SOPA)](https://sopawards.com/wp-content/uploads/2020/08/SOPA-2020-Awards-Winner-List.pdf), _Honorable Mention for Excellence in Human Rights Reporting Global in 2020_


Computer Languages {#computer_languages}
--------------------------------------------------------------------------------

```{r}
CV %>% print_skill_bars()
```

 Human Languages  {#human_languages}
--------------------------------------------------------------------------------

```{r}
CV %>% print_lang_skill_bars()
```


Disclaimer {#disclaimer}
--------------------------------------------------------------------------------

Made with the R package [**datadrivencv**](https://github.com/nstrayer/datadrivencv). 

Last updated on `r Sys.Date()`.


Main
================================================================================

Eva Xiao {#title}
--------------------------------------------------------------------------------

```{r}
# Note the special double pipe so we modify the CV object in place
CV %<>% print_text_block("intro") 
```



Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('education')
```



Work Experience {data-icon=laptop}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('work_experience')
```

Clips {data-icon=newspaper}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_clips_section('by_me_press')
```